### ISSUE TITLE
Not getting the transaction hash after executing a transaction

### ISSUE THREAD

**Issue by nikhilasrani** [buidler-labs/hashgraph-react-wallets#1]
I am trying to execute an approve allowance transaction with the DappSigner. I am referring to the documentation [here](https://buidler-labs.github.io/hashgraph-react-wallets/guides/execute-transactions.html)

```
 
        import { AccountAllowanceApproveTransaction } from "@hashgraph/sdk";
        import { useWallet, useWatchTransactionReceipt } from "@buidlerlabs/hashgraph-react-wallets";
       
       const Component = () => {
        ...
        const { signer } = useWallet();
        ...
        const approveTokenTrx = await new AccountAllowanceApproveTransaction()
          .approveTokenAllowance(
            ASSET_HTS_ACCOUNT_ID,
            ACCOUNT_ID,
            LENDING_POOL_CONTRACT_ID,
            AMOUNT
          )
          .setMaxTransactionFee(MAX_TRANSACTION_FEE)
          .freezeWithSigner(signer);

        let response = await approveTokenTrx.executeWithSigner(signer);
        const receipt = await response.getReceiptWithSigner(signer);
    }
```

I'm currently getting a TypeScript error in my IDE on every instance where `signer` is used.

```
Argument of type 'HWBridgeSigner | null' is not assignable to parameter of type 'Signer'.
```

Connect Wallet works properly and I am able to log the DappSigner. When the function that calls the code with `executeWithSigner` runs, The transaction shows up in the wallet correctly and I am able to accept it and the wallet shows it as successful but I do not see any console logs or activity after it. not sure what's wrong or what the issue is.  My issue is only when it comes to executing any type of transaction in this way. Happy to provide more details and some example snippet if needed. Please let me know.

**Comment by nikhilasrani** [comment]
I do get a response after a very long time in my console saying the request timed out

```
VM3742 Supply.tsx:145 Error: Error executing transaction or query: 
{
  "txError": {
    "name": "Error",
    "message": "Request expired. Please try again.",
    "stack": "Error: Request expired. Please try again.\n    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@walletconnect/utils/dist/index.es.js:167:7794)"
  },
  "queryError": {
    "name": "Error",
    "message": "(BUG) Query.fromBytes() not implemented for type getByKey",
    "stack": "Error: (BUG) Query.fromBytes() not implemented for type getByKey\n    at Query.fromBytes (webpack-internal:///(app-pages-browser)/./node_modules/@hashgraph/sdk/src/query/Query.js:138:19)\n    at DAppSigner._tryExecuteQueryRequest (webpack-internal:///(app-pages-browser)/./node_modules/@hashgraph/hedera-wallet-connect/dist/src/lib/dapp/DAppSigner.js:182:77)\n    at DAppSigner.call (webpack-internal:///(app-pages-browser)/./node_modules/@hashgraph/hedera-wallet-connect/dist/src/lib/dapp/DAppSigner.js:202:40)\n    at async onSupply (webpack-internal:///(app-pages-browser)/./src/app/dashboard/_components/Actions/Supply/Supply.tsx:74:28)"
  }
}
    at DAppSigner.call (DAppSigner.js:207:15)
    at async onSupply (Supply.tsx:101:13)
```
 
  and `{context: 'client'} 'Request expired. Please try again.'`, but this is a long time after the transaction was shown as successful in the wallet. 
  
  
  I am also posting the configuration and package details below since they could be relevant/useful.
  
  ```
  import {
  HWBridgeProvider,
  HWCConnectionStrategy,
} from "@buidlerlabs/hashgraph-react-wallets";
import {
  HashpackConnector,
  KabilaConnector,
} from "@buidlerlabs/hashgraph-react-wallets/connectors";
import { HederaTestnet } from "@buidlerlabs/hashgraph-react-wallets/chains";
import { appMetadata } from "./appMetadata";
import DashboardLoadingAnimation from "@/app/dashboard/_components/DashboardLoadingAnimation";

const ReactWalletsProvider = ({ children }: any) => {
  const WALLETCONNECT_PROJECT_ID =
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || "";

  return (
    <HWBridgeProvider
      metadata={appMetadata}
      projectId={WALLETCONNECT_PROJECT_ID}
      connectors={[HashpackConnector, KabilaConnector]}
      chains={[HederaTestnet]}
      strategies={[]}
      LoadingFallback={DashboardLoadingAnimation}
    >
      {children}
    </HWBridgeProvider>
  );
};

export default ReactWalletsProvider;
```

```
    "@hashgraph/hedera-wallet-connect": "^1.3.2",
    "@hashgraph/proto": "^2.15.0",
    "@hashgraph/sdk": "^2.40.0",
    "@buidlerlabs/hashgraph-react-wallets": "^2.1.2",

  ````

**Comment by vla-dev** [comment]
> I am trying to execute an approve allowance transaction with the DappSigner. I am referring to the documentation [here](https://buidler-labs.github.io/hashgraph-react-wallets/guides/execute-transactions.html)
> 
> ```
>  
>         import { AccountAllowanceApproveTransaction } from "@hashgraph/sdk";
>         import { useWallet, useWatchTransactionReceipt } from "@buidlerlabs/hashgraph-react-wallets";
>        
>        const Component = () => {
>         ...
>         const { signer } = useWallet();
>         ...
>         const approveTokenTrx = await new AccountAllowanceApproveTransaction()
>           .approveTokenAllowance(
>             ASSET_HTS_ACCOUNT_ID,
>             ACCOUNT_ID,
>             LENDING_POOL_CONTRACT_ID,
>             AMOUNT
>           )
>           .setMaxTransactionFee(MAX_TRANSACTION_FEE)
>           .freezeWithSigner(signer);
> 
>         let response = await approveTokenTrx.executeWithSigner(signer);
>         const receipt = await response.getReceiptWithSigner(signer);
>     }
> ```
> 
> I'm currently getting a TypeScript error in my IDE on every instance where `signer` is used.
> 
> ```
> Argument of type 'HWBridgeSigner | null' is not assignable to parameter of type 'Signer'.
> ```
> 
> Connect Wallet works properly and I am able to log the DappSigner. When the function that calls the code with `executeWithSigner` runs, The transaction shows up in the wallet correctly and I am able to accept it and the wallet shows it as successful but I do not see any console logs or activity after it. not sure what's wrong or what the issue is. My issue is only when it comes to executing any type of transaction in this way. Happy to provide more details and some example snippet if needed. Please let me know.

Hey @nikhilasrani,

You can use type assertion to get rid of any typescript errors:
```jsx
import { Signer } from "@hashgraph/sdk";

const Component = () => {
    const wallet = useWallet();
    const signer = wallet.signer as Signer;
    ...
}
```

The transaction execution looks good to me, excepting this line:
```jsx
const receipt = await response.getReceiptWithSigner(signer);
```

If you remove it, you should be able to log the `response` from `await approveTokenTrx.executeWithSigner(signer);` which is a `TransactionResponse` type that has a `transactionId` property. Based on it, you can integrate [`useWatchTransactionReceipt`](https://buidler-labs.github.io/hashgraph-react-wallets/hooks/use-watch-transaction-receipt.html) to get the transaction status async.

Lmk if you manage to make it work.

Cheers!

**Comment by vla-dev** [comment]
Please note that this transaction execution method is only compatible with Hedera native wallets. If you plan to integrate any other EVM-compatible wallets such as Metamask or Coinbase, I recommend using [useApproveTokenAllowance](https://buidler-labs.github.io/hashgraph-react-wallets/hooks/use-approve-token-allowance.html), which will cover all the cases.

**Comment by nikhilasrani** [comment]
@vla-dev I tried both ways, the `executeWithSigner` and the `useApproveTokenAllowance` way, I get console logs working until the line where approve or execute transaction runs, after that, the console is blank and nothing in the function executes after it. I do not get a `transactionIdOrHash` response.

**Comment by nikhilasrani** [comment]
I'm using the `HashpackConnector` for the wallet side of things and I'm using Next.js to run my app but the component is dynamically imported and is entirely client side. I think there is something wrong with the way I have configured the library, happy to share more details as required to debug this.

**Comment by nikhilasrani** [comment]
```
  console.log("before approve");
      const transactionIdOrHash = await approve(TOKENS, SPENDER);
      if (transactionIdOrHash && typeof transactionIdOrHash === "string") {
        watch(transactionIdOrHash, {
          onSuccess: (transaction) => {
            // do stuff
            console.log(transaction);
            return transaction;
          },
          onError: (transaction, error) => {
            // do stuff
            console.log(transaction, error);
            return transaction;
          },
        });
        console.log("after approve", transactionIdOrHash);
      }
   ```
   
   ^This is what I am running, after a long time, I get this error
   ```
   VM2493 Supply.tsx:157 Error: Error executing transaction or query: 
{
  "txError": {
    "name": "Error",
    "message": "Request expired. Please try again.",
    "stack": "Error: Request expired. Please try again.\n    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@walletconnect/utils/dist/index.es.js:167:7794)"
  },
  "queryError": {
    "name": "Error",
    "message": "(BUG) Query.fromBytes() not implemented for type getByKey",
    "stack": "Error: (BUG) Query.fromBytes() not implemented for type getByKey\n    at Query.fromBytes (webpack-internal:///(app-pages-browser)/./node_modules/@hashgraph/sdk/src/query/Query.js:138:19)\n    at DAppSigner._tryExecuteQueryRequest (webpack-internal:///(app-pages-browser)/./node_modules/@hashgraph/hedera-wallet-connect/dist/src/lib/dapp/DAppSigner.js:182:77)\n    at DAppSigner.call (webpack-internal:///(app-pages-browser)/./node_modules/@hashgraph/hedera-wallet-connect/dist/src/lib/dapp/DAppSigner.js:202:40)\n    at async approveTokensAllowance (webpack-internal:///(app-pages-browser)/./node_modules/@buidlerlabs/hashgraph-react-wallets/lib/actions/tokens.actions.js:88:24)"
  }
}
    at DAppSigner.call (DAppSigner.js:207:15)
    at async approveTokensAllowance (tokens.actions.js:88:24)
   
```

    
  could this be related to some versioning issue?
  `(BUG) Query.fromBytes() not implemented for type getByKey`
  
  seems like it could be related to this specific issue
  https://github.com/hashgraph/hedera-wallet-connect/issues/186

**Comment by nikhilasrani** [comment]
closing this issue as execute transactions are working as expected. thank you @vla-dev for your help & support!
