### ISSUE TITLE
Add a sample.env file in the demo directory containing the required values

### ISSUE THREAD

**Issue by SimiHunjan** [buidler-labs/hashgraph-react-wallets#7]
The readme instructs the developer to create a .env file in the root of the demo directory. Consider adding a sample.env file so that the dev doesn't have to create the file and copy paste the values that are required to be populated in it.

**Comment by vla-dev** [comment]
Added on [3972507](https://github.com/buidler-labs/hashgraph-react-wallets/commit/39725076326f7e627e83a324476a7aa43bded10b).
